### ISSUE TITLE
RFID - Conditional card not working

### ISSUE THREAD

**Issue by snakefaith** [aartse/athom.zipato#81] opened 2023-09-04 05:26 UTC
Hello

The rfid reader doesnt work under homey 2023.
The zipato app at homey settings is work change the status  (home/away) when i take the card the reader but the flow not works.
The flow is when the user is home and the specicified user at home then presence mark specified user as home.
this flow worked with homey2019.
what do you think the problem might be?

**Comment by aartse** [comment] 2023-09-30 14:07
hi, i have the old homey pro so i cannot check the issue. but there was a known issue with the state triggers. This is fixed in the test version of the app: https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/. maybe you can install this version to check if this fixes the issue you are having.

also you can check the app settings if the tags and users are correctly setup.

**Comment by aartse** [comment] 2023-10-02 10:17
update is released to the stable channel of the app store. so it is not needed to install the test version.

**Comment by snakefaith** [comment] 2023-10-03 05:32
Hello
The problem is same. The app change state immediately, but not send the homey.
![Zipato](https://github.com/aartse/athom.zipato/assets/112923909/35d114f9-e73c-40bd-9671-5afb2e65b191)

**Comment by aartse** [comment] 2023-10-06 08:13
does the 'current status' in the zipato settings change when you came and leave home?

i will try the given flow maybe there is something wrong with the 'and' condition.

**Comment by snakefaith** [comment] 2023-10-06 09:53
Yes zipato settings change correctly

**Closed** 2024-02-25 16:39 UTC

**Comment by aartse** [comment] 2024-02-25 16:41
@snakefaith I have found the cause of this problem. the app will be updated during the week as soon as it has been reviewed by athom.
