### ISSUE TITLE
Zipato Indoor Siren does not have multi sound support in Homey.

### ISSUE THREAD

**Issue by depeej** [aartse/athom.zipato#18] opened 2018-08-07 16:16 UTC
A week ago I bought the Zipato Indoor Siren, which is supported by this App in my Homey. My purpose of the siren was, to use it in multiple flows. As a siren when a movement is triggerd by the Fibaro multisensor, but also as a chime when someone rings my doorbell.

Unfortunately I had to found out that this Homey app only support the 'siren' sound. It would be great if this could be upgrated to the multiple (6) sounds that are supported by the syren itself.

Thanks in advance!

Pim

**Comment by depeej** [comment] 2018-09-10 15:36
Hi aartse, thanks for your reply! According to the manual the siren should have 6 sounds:
- Emergency sound
- Fire alert
- Police car sound
- Door chime
- beep beep (ideal for alarm delays)

Would be great if these sounds could be implemented in the Homey app! Thank you a lot in advance!
Pim

![img_1243](https://user-images.githubusercontent.com/41466684/45307617-bfb93600-b51f-11e8-9cfb-aaa57ac2effe.jpg)
![img_1242](https://user-images.githubusercontent.com/41466684/45307618-bfb93600-b51f-11e8-8657-0b75c65b7051.jpg)

**Comment by kaz911** [comment] 2018-09-19 23:03
I'm in the same boat - would love to get the other sounds to work on the Zipato. It is the "Multisound Indoor Siren".

Messages: 
The device supports using SWITCH_MULTILEVEL SET to play the sound. 

The sound ID is defined as follows:
1 or 255: Emergency sound.
2: Fire alert.
3: Ambulance sound.
4: Police car sound.
5: Door chime.
6~99: Beep Beep.
0: means stop the sound

https://www.zipato.com/product/multisound-indoor-siren

https://www.zipato.com/wp-content/uploads/2015/09/ph-pse02-Zipato-Siren-User-Manual-v1.2.pdf

**Comment by MickiHindsgaul** [comment] 2018-10-11 17:50
Hi, 

I also have an issue with the indoor siren (part no PH-PSE02.EU) and the app does not recognise it as an Zipato device, but as an generic Z-wave plus device!

best regards, Micki

**Comment by aartse** [comment] 2018-10-17 09:02
hi @MickiHindsgaul, when the device is added as a generic Z-wave plus device, homey has no app for this product. Homey searches for an app with 3 values: manufacturer_id, product_type_id, product_id.

can you send me this 3 id's for your device? you can find the id's in the device settings ->node information.

**Comment by depeej** [comment] 2018-10-17 09:38
Hi aartse, could you give us a status update about the siren? Thanks!

**Comment by aartse** [comment] 2018-10-17 10:10
hi @depeej, I will look at it soon

**Comment by aartse** [comment] 2018-10-28 23:31
i updated code in github for the beta branch to support multiple sounds. because I do not have this device in my possession, I can not test whether the adjustments work. Can somebody test this in the beta version of the app when the update is approved by athom (usually in some days). When it works, i'll close this issue.

**Comment by aartse** [comment] 2018-11-04 12:17
updated beta version is published

**Comment by depeej** [comment] 2018-11-04 12:31
Hi aartse, unfortunately the sounds does not work. After a few tests the app crashed, I sended you the log. ID number: f272afe8-90ab-48d5-b86b-093f563aaeba.

**Comment by aartse** [comment] 2018-11-04 14:17
Ok, i will check this

**Comment by aartse** [comment] 2018-11-04 20:19
hi @depeej, i received a report from a crashed app. i don't know if it is yours. but i added an extra check if the device doesn't support the command for changing the sound. This is added to preventing the app crashes. 

Can you install the app from the beta branch from github to check if this is the cause of your crash? If you do'nt know how to install the app from github, i'll send the app to athom for an update, but this can take some day's.

**Comment by depeej** [comment] 2018-11-04 20:50
Hi aartse, I don’t know how to update from GitHub. Please sent the update to Athom. Thank you a lot for your help. 

Pim

**Comment by depeej** [comment] 2018-11-19 14:21
hi @aartse: Is the new beta release active at Athom?

**Comment by aartse** [comment] 2019-01-07 21:58
@depeej new beta is released with a fix for multi sound.
@MickiHindsgaul your device is also added to this app.

**Closed by aartse** 2019-01-07 21:58 UTC
Labels: available in next beta release

**Comment by depeej** [comment] 2019-01-09 07:42
Hi @aartse: I have tested the new Beta. It does not matter which sound you choose; my multisiren puts the siren on when you select one. According to my manual it should be able to have the multisounds. I can sent mine over to you for testing? I live in Brabant, the Netherlands.
Pim
